x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: "prge_postgis"
    container_name: prge_postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data



  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_2025_geoserver'
    container_name: prge-2025-geoserver-${ENV_NAME}
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - ../.tmp/data-${ENV_NAME}:/opt/geoserver_data



  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    image: 'prge_2025_fastapi'
    container_name: prge_2025_fastapi-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${FASTAPI_PORT}:10000


  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile_local
    image: 'prge_2025_nginx'
    container_name: prge_2025_nginx-${ENV_NAME}
    ports:
      - 8081:80


volumes:
    postgis-local-data:
