name: build and push and deploy
on:
  push:
    branches:
      - env-test

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo "Witaj"



      - name: Uruchom Å›rodowisko docker-compose
        env:
          POSTGRES_DB: ${{sercrets.POSTGRES_DB}}
          POSTGRES_USER: ${{sercrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{sercrets.POSTGRES_PASSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yml --env-file .env -p local-prge up --build -d

      
